### ISSUE TITLE
RANDOM() sub not working for metadata

### ISSUE THREAD

**Issue by x2012x** [michaelkeeling/cucumber-grpc-api-assistant#5]
Specifying `{RANDOM()}` as a metadata value is not substituted out for a random value, the raw value '{RANDOM()}` is sent as the metadata value.

```
    And the grpc metadata keys and values are set as
      | key               | value        |
      | some_key          | {RANDOM()} |
```

**Comment by michaelkeeling** [comment]
[I've added an explicit test for this and it appears to be working as expected](https://github.com/michaelkeeling/cucumber-grpc-api-assistant/blob/master/features/working_with_metadata.feature#L40).  I'm going to assume it was fixed at some point between when you noticed the problem and now.
